### ISSUE TITLE
Exception trying to add an existing keyword containing "&" character

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-geonode#13]
We are using GeoNode rest API to upload a layer in geonode and to save some metadata information (and keywords).
Normally when we upload a layer with an existing keyword everything works fine.
But if the name of the existing keyword contain the chracter "&" eg Transport&Travel we obtain an error.
[https://app.zenhub.com/files/300204757/d23cf626-be9f-46c3-b752-82b6fabd1acd/download](https://app.zenhub.com/files/300204757/d23cf626-be9f-46c3-b752-82b6fabd1acd/download)

**Comment by mattiagiupponi** [comment]
PR has been merged on GeoNode master
