### ISSUE TITLE
GeoNode: hide register and signin buttons

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-geonode#18]
Customer is asking to hide the Register and Sign in buttons (elements B in the following picture). 
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/a0627ecd-90dd-4e13-aa7d-2b16d768eee2)
He would allow this in a later step of the project.

**Comment by chpicone** [comment]
After discussion with @allyoucanmap and @giohappy we agree to hide just the *register* button and to mantain the *sigin* button (mainly for the admin user)

**Comment by chpicone** [comment]
We still have the "Register" button visible!

![image](https://user-images.githubusercontent.com/2872823/122782742-4266a680-d2b1-11eb-8adc-5422ea13bbef.png)

**Comment by chpicone** [comment]
Can you take a look @marthamareal

**Comment by marthamareal** [comment]
Yes this can be set using a variable, however, i had added a default to be false [here](https://github.com/geosolutions-it/oaw-geonode/pull/29/commits/48ee98f3df960c305f3e663463bd2cff5f8bf926). but I think the change was lost on resolving conflicts.

**Comment by mattiagiupponi** [comment]
> Yes this can be set using a variable, however, i had added a default to be false [here](https://github.com/geosolutions-it/oaw-geonode/pull/29/commits/48ee98f3df960c305f3e663463bd2cff5f8bf926). but I think the change was lost on resolving conflicts.

Hi @marthamareal !
Even if is not visible in the PR (my bad!) the variable is correctly set in the `settings.py` file:
https://github.com/geosolutions-it/oaw-geonode/blob/f04527e1c1749ae9fe38bc991abe28d7b81931d8/oaw_geonode/settings.py#L61
In order to hide the item, should we put it as `True`?

**Comment by marthamareal** [comment]
> In order to hide the item, should we put it as `True`?

No @mattiagiupponi  it should be false, @chpicone could we check if this is variable `ACCOUNT_OPEN_SIGNUP` set in the project environment?
