### ISSUE TITLE
GeoNode: customize headlines in the home page

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-geonode#19]
Customer is asking to customize headline and subheadline in the home page.
Refer to the elements C and D in the following picture:
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/198f462c-f85d-4998-b418-36e252740230)
- headline  (C)
  - German: Sammlung Woldan-HGIS
  - English: Woldan Collection-HGIS
- subheadline (D)
  - German: Historische Geodaten, Altkarten und Ansichten
  - English:  Historical Geodata, Old Maps and Views

**Comment by marthamareal** [comment]
@chpicone basing on UI in 3.2.x, the above screen now looks like this.

**Comment by chpicone** [comment]
I think better:
Welcome -> Woldan Collection-HGIS
GeoNode is an open source platform for sharing geospatial data and maps -> Historical Geodata, Old Maps and Views

**Comment by marthamareal** [comment]
On using the custom theme settings in the db, here are examples 
1. with slide show
![slideshow](https://user-images.githubusercontent.com/20810749/120333340-43329b00-c2f8-11eb-901c-27d0dbf7d1bb.png)

2. no slide
![noslide](https://user-images.githubusercontent.com/20810749/120333446-5d6c7900-c2f8-11eb-9d7c-916e0c1d3c9a.png)

**Comment by chpicone** [comment]
@marthamareal if it is possible I think better to have the subheadline (Historical Geodata, Old Maps and Views) in the screenshot 1 with a bigger font size.
For both (headline and subheadline) I am asking you to center them in the page (horizontally).

**Comment by chpicone** [comment]
Just the headline... subheadline is already centered!

**Comment by marthamareal** [comment]
@chpicone  Here is a screenshot with above requested changes
![Uploading news.png…]()
