### ISSUE TITLE
GeoNode: remove MyResources and MyLinks from the Search page

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-geonode#22]
Customer is asking to remove these sections from the home page (when Advanced search panel is visible):
- gnhome.myresources
- gnhome.mylink

![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/db7783ea-dc55-42cd-9de3-c54b8063cabd)

Attention: the displayed elements are not correctly setted (in english). In Italian it seems correct:
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/4a687128-bd5b-4567-917a-dfb4eb6a719f)

**Comment by chpicone** [comment]
With GeoNode 3.2.x this issue should no longer be needed.
So, we have just to do a quick check.

**Comment by marthamareal** [comment]
This is not needed with Geonode 3.2.x and mapstore-client 2.1.x
