### ISSUE TITLE
OAW: custom project based on GeoNode 3.2.x

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-geonode#26]
Currently custom project is based on master branch of GeoNode.
We need to make it based on GeoNode 3.2.x.

**Comment by marthamareal** [comment]
@chpicone, From the conversation I have had with @allyoucanmap, Updating Geonode to 3.2.x requires us to update mapstore-client to 2.1.x. Also, we will not be needing to install mapstore-adapter since its included in mapstore-client on branch 2.1.x
