### ISSUE TITLE
Deployment of the new version of GeoNode/Airflow

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/oaw-geonode#40]
The deployment of the new version of GeoNode/Airflow is needed, with the following items:
- Airflow: request to publish layer with attribute “IsPublished” set to False
- Airflow: more clear log message in case of missing metadata
- GeoNode: Fix for the hierarchical keywords

**Comment by randomorder** [comment]
@lpasquali please sync with @mattiagiupponi when he comes back on Monday to schedule the deployment

**Comment by lpasquali** [comment]
Hello @mattiagiupponi let me know when we can sync about this update

**Comment by mattiagiupponi** [comment]
> Hello @mattiagiupponi let me know when we can sync about this update

Hey  @lpasquali 
For me, it's fine whenever you want, but not today (I'm quite busy on another issue)
