### ISSUE TITLE
GeoNode upgrade from v3 to v4: layer URL address changed 

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/oaw-geonode#48]
After upgrading from the previous GeNode v3 to GeoNode v4. Client is saying that the link to the layer has changed and it is not working anymore.
For example, before it was 
https://hgis.woldan.oeaw.ac.at/layers/AC03869742:geonode:AC03869742
Now it is
https://hgis.woldan.oeaw.ac.at/catalogue/#/dataset/633

The issue is that the client's Digital Library application automatically creates the link to the layer in GeoNode based on the ACNumber (`AC03869742 `in the example). 
This is written in the Geonode Dataset Metadata  Store: `AC03869742 `
Name: `AC03869742 `
Typename: `geonode:AC03869742` 

To fix that, we could develop and install a customization client side for OAW specific project to allow the use of the ACnumber  in the link (as it was before ) instead of Id

**Comment by mattiagiupponi** [comment]
Hi @EddyCatt 
Here is an example of the new behavior, do you think it looks good?
![oaw_redirect](https://user-images.githubusercontent.com/51856725/235096978-d7ae2f91-9ee5-4d7a-ad41-7f199295cf11.gif)

**Comment by mattiagiupponi** [comment]
Tests went well from QA side and client side, I'm closing this issue
